feat: add appointments and clinic availability
The-CSC207-Group/Project207 pull request #13
Opened 2022-08-05 18:53 UTC by DanielDervishi

The goal of this pr is to provide secretaries the ability to schedule non-conflicting appointments between doctors and patients within a frame of availability provided by a clinic. This is achieved by:

- Adding and storing weekly re-occurring hours of operation (also known as availability) under the clinic that is mutable by an admin and is used to determine when appointments can be booked.
- Adding the ability for secretaries to book appointments between a doctor and patient on a given day, provided that they do not overlap with another appointment and that they fall within the clinic's operating hours (availability).

2022-08-08 04:18 UTC, ahmedkhalf requested changes
Overall great code. Very few minor mistakes are to be fixed. Good job guys.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/entities/UniversalTimeBlock.java
> +public interface UniversalTimeBlock {
Interface is missing javadocs

2022-08-08 04:18 UTC, ahmedkhalf commented on src/entities/UniversalTimeBlockWithDay.java
> +public interface UniversalTimeBlockWithDay extends UniversalTimeBlock {
Interface missing javadocs

2022-08-08 04:18 UTC, ahmedkhalf commented on src/entities/UniversalTimeBlock.java
> +    LocalTime startTime();
Method is missing javadocs. Furthermore, method should be named `getStartTime`. What happened to java conventions?

2022-08-08 04:18 UTC, ahmedkhalf commented on src/entities/UniversalTimeBlock.java
> +    LocalTime endTime();
Method is is missing javadocs. Furthermore, method should be named `getEndTime`. What happened to java conventions?

2022-08-08 04:18 UTC, ahmedkhalf commented on src/entities/UniversalTimeBlock.java
> +    DayOfWeek dayOfWeek();
Method is missing javadocs. Furthermore, method should be named `getDayOfWeek`. What happened to java conventions?

2022-08-08 04:18 UTC, ahmedkhalf commented on src/entities/UniversalTimeBlockWithDay.java
> +    LocalDate date();
Method is missing javadocs

2022-08-08 04:18 UTC, ahmedkhalf commented on src/entities/UniversalTimeBlockWithDay.java
> +    default DayOfWeek dayOfWeek(){
Method is missing  `{@inheritDoc}` javadoc

2022-08-08 04:18 UTC, ahmedkhalf commented on src/entities/TimeBlock.java
Remove this comment

2022-08-08 04:18 UTC, ahmedkhalf commented on src/entities/TimeBlock.java
> +
Too many blank lines at the end of the file. (max: 1).

2022-08-08 04:18 UTC, ahmedkhalf commented on src/entities/Clinic.java
> +    public void addClinicHours(Availability clinicHours) {this.clinicHours.add(clinicHours);}
Expand this method onto three lines.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/entities/Availability.java
>  /**
Remove comment saying `PHASE 2 FILE` at the start of this file.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/entities/Appointment.java
Remove comment saying `PHASE 2 FILE` at the start of this file.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/dataBundles/TimeBlockData.java
>  package dataBundles;
Remove comment saying `PHASE 2 FILE` at the start of this file.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/entities/TimeBlock.java
>      }
Useless methods. Already local time. Please remove the `endTimeToLocal`, `startTimeToLocal` methods.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/dataBundles/TimeBlockData.java
>      }
Useless methods. Already local time. Please remove the `endTimeToLocal` and `startTimeToLocal` methods.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/entities/Availability.java
>      }
Useless methods. `getDoctorEndTime` and `getDoctorStartTime` do the same thing as `getStartTime` and `getEndTime`.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/dataBundles/AvailabilityData.java
>      }
Useless methods. `getDoctorStartTime` and `getDoctorEndTime` do the same thing as  `getStartTime` and `getEndTime`.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/dataBundles/AvailabilityData.java
>  package dataBundles;
Remove `PHASE 2 FILE` comment at the start of the file.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/dataBundles/AppointmentData.java
>  package dataBundles;
Remove `PHASE 2 FILE` comment at the start of the file.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/presenters/entityViews/AppointmentView.java
>  package presenters.entityViews;
Remove `PHASE 2 FILE` comment at the start of this file.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/presenters/entityViews/AvailabilityView.java
>  package presenters.entityViews;
Remove `PHASE 2 FILE` comment at the start of this file.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/presenters/entityViews/AvailabilityView.java
> +        return dayOfWeekUtils.dayOfWeekToString(item.getDayOfWeek()) + ": " + item.startTime() + " to " + item.endTime();
Line exceeds 120 characters.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/presenters/entityViews/ClinicView.java
> +    public String viewClinicHours(ClinicData item){
This method is too large. The `LinkedHashMap` should be returned from the `DayOfWeekUtils` file and take one line to create in this file.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/presenters/response/AbsenceDetails.java
> +//public class AbsenceDetails {
This file should be removed if it's not going to be used.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/presenters/response/AvailabilityDetails.java
> +public class AvailabilityDetails {
This is a not a correct response, please refer to the `README.md` file of this submodule for how to create a correct response class automatically using java record.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/presenters/screenViews/ClinicScreenView.java
> +
Remove that empty line between javadoc and method.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/presenters/screenViews/ClinicScreenView.java
> +        ArrayList<DayOfWeek> dayOfWeeks = new ArrayList<>(Arrays.asList(DayOfWeek.MONDAY, DayOfWeek.TUESDAY,
As previously mentioned this arraylist, or LinkedHashMap should be gotten from the `dayOfWeekUtils` directly.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/presenters/screenViews/ScreenView.java
> +    protected LocalTime showLocalTimePrompt(){
Add an empty line before the method.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/presenters/screenViews/SecretaryScreenView.java
> +        errorMessage("Error Booking Appointment.");
Please make this error message as explicit as the javadoc. I.e. error message too vague.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/presenters/screenViews/SecretaryScreenView.java
> +    }
Add an empty line after this method.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/presenters/screenViews/SecretaryScreenView.java
> +        errorMessage("Can not book today as there is no availability.");
Use correct English.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/utilities/DayOfWeekUtils.java
> +        }};
As mentioned earlier, a method should be created to get this LinkedHashMap.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/utilities/TimeUtils.java
>  import java.time.*;
Remove the `PHASE 2 FILE` comment at the start of this file.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/utilities/TimeUtils.java
>      public TimeBlock createTimeBlock(Integer year, Integer month, Integer day, Integer hour, Integer minute, Integer lenOfAppointment){
Line exceeds 120 chars.  Too many arguments: year, month, day can be replaced by local date. Hour, minute, can be replaced by local time.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/useCases/DoctorManager.java
>  /**
On line 38 of this file it says pending implementation in phase 2???? (Sry intellij doesn't allow me to comment on non-edited lines).

2022-08-08 04:18 UTC, ahmedkhalf commented on src/useCases/AppointmentManager.java
>                                             Integer lengthOfAppointments) {
Too many arguments: year, month, day can be replaced by local date. Hour, minute, can be replaced by local time.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/useCases/AppointmentManager.java
> +                                         Integer hour, Integer minute, Integer lengthOfAppointments) {
Too many arguments: year, month, day can be replaced by local date. Hour, minute, can be replaced by local time.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/useCases/AppointmentManager.java
> +        database.getAppointmentDatabase().remove(appointmentData.getAppointmentId());
The appointment should only be removed inside the if statement.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/useCases/AppointmentManager.java
> +        appointmentDatabase.add(selectedAppointment);
Once line 93 is moved inside the if statement, line 99 should be deleted.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/useCases/AppointmentManager.java
> +            appointmentDatabase.add(new Appointment(proposedTime, appointmentData.getDoctorId(), appointmentData.getPatientId()));
line too long. (max 120 chars).

2022-08-08 04:18 UTC, ahmedkhalf commented on src/useCases/AppointmentManager.java
>          return getAppointments().stream()
if you are going to have a `getAllPatientAppointments` method, then if it's fair to say you should have `getAllDoctorAppointments` method here. I.e. be consistent.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/useCases/AppointmentManager.java
> +        return doesNotOverlapWithDoctorsAppointments(timeBlock, doctorData) && strictlyOverlapsWithClinicHours(timeBlock);
Line over 120 chars.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/useCases/AppointmentManager.java
> +    private boolean isWithinDate(LocalDate time1, LocalDate time2, UniversalTimeBlockWithDay timeBlock) {
This method is not being used? Any reason why?

2022-08-08 04:18 UTC, ahmedkhalf commented on src/useCases/AppointmentManager.java
> +    private boolean doesNotOverlapWithDoctorsAppointments(UniversalTimeBlockWithDay timeBlock, DoctorData doctorData) {
Im not quite sure, how line 174 until the end of the file work. I know they are private methods but maybe a javadoc with a little explanation will help. If the tests cover all edge cases though, then I will trust this code.

2022-08-08 04:18 UTC, ahmedkhalf commented on test/AppointmentManagerTests.java
> +                        LocalTime.of(17, 0))))));
Why are you reeating the same code for every test.... Use helper methods.

2022-08-08 04:18 UTC, ahmedkhalf commented on test/AppointmentManagerTests.java
> +        DoctorData doctorData = new DoctorManager(originalDatabase).createDoctor("test1", "test1");
I refuse to review the tests any further. This is not sane.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/controllers/SecretaryLoadedPatientController.java
>              ArrayList<AppointmentData> appointments = appointmentManager.getPatientAppointments(patientData);
`showNoUserAppointmentsMessage` should be shown if patient has no appointments.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/controllers/SecretaryLoadedPatientController.java
>          };
On line 159, why is there no error handling? What happens after rescheduleAppointment returns false?

2022-08-08 04:18 UTC, ahmedkhalf commented on src/controllers/SecretaryLoadedPatientController.java
> +        }else {
a presenter and a check for no appointments should also be added.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/controllers/PatientController.java
>              ArrayList<AppointmentData> appointments = appointmentManager.getPatientAppointments(patientData);
a check and presenter method should be added, for when there are no appointments.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/controllers/DoctorController.java
>      }
for all three view methods from line 71 to 89 a check and no appointments message should be added.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/controllers/ClinicController.java
> +            if (availabilityDetails == null || availabilityDetails.getStartTime().isAfter(availabilityDetails.getEndTime())){
Line exceeds 120 chars.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/controllers/ClinicController.java
> +            clinicManager.changeClinicHours(availabilityDetails.getDayOfWeek(), availabilityDetails.getStartTime(), availabilityDetails.getEndTime());
Line exceeds 120 chars.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/presenters/screenViews/ClinicScreenView.java
> +        errorMessage("Invalid entry.");
Please be more descriptive.

2022-08-08 04:18 UTC, ahmedkhalf commented on src/presenters/screenViews/ClinicScreenView.java
> +        errorMessage("Invalid selection.");
Please be more descriptive.

2022-08-08 17:12 UTC, solomon-the-wise commented on src/entities/UniversalTimeBlock.java
> +    LocalTime startTime();
It causes annoying naming conflicts. Not sure if its worth fixing. the other option was getStartTimeLocalTime but this is really long

2022-08-08 17:12 UTC, solomon-the-wise commented on src/entities/UniversalTimeBlock.java
> +    LocalTime endTime();
naming conflicts as above

2022-08-08 17:16 UTC, solomon-the-wise commented on src/entities/UniversalTimeBlock.java
> +    DayOfWeek dayOfWeek();
naming conflicts

2022-08-08 17:24 UTC, solomon-the-wise commented on src/entities/TimeBlock.java
>      }
its in LocalDateTime not LocalTime

2022-08-09 17:50 UTC, ahmedkhalf requested changes

2022-08-09 17:50 UTC, ahmedkhalf commented on src/controllers/SecretaryLoadedPatientController.java
> +                LocalDateTime startTime = LocalDateTime.of(day.getYear(), day.getMonthValue(), day.getDayOfMonth(),
What happens when day is null? This code smells like null pointer errors. What happens when time is null? Again null pointer errors. Furthermore, if the call to  `getPatientAppointments` returns an empty list a relevant presenter method NoUserAppointmentsMessage should be displayed and the command should not continue.

2022-08-09 17:50 UTC, ahmedkhalf commented on src/controllers/PatientController.java
>              ArrayList<AppointmentData> appointments = appointmentManager.getPatientAppointments(patientData);
A check and presenter method should be added, for when there are no appointments.

2022-08-09 17:50 UTC, ahmedkhalf commented on src/controllers/DoctorController.java
> +            doctorScreenView.viewAppointments(new AppointmentManager(getDatabase()).getSingleDayAppointment(doctorData, viewDate));
A check and no appointments message should be added.

2022-08-09 17:50 UTC, ahmedkhalf commented on src/controllers/DoctorController.java
> +                .getDoctorAppointments(doctorData));
A check and no appointments message should be added.

2022-08-09 18:07 UTC, DanielDervishi commented on src/controllers/DoctorController.java
> +                .getDoctorAppointments(doctorData));
This command should have been removed in the first place.

2022-08-10 02:02 UTC, ahmedkhalf approved these changes

2022-08-10 15:06 UTC, Hepaul7 approved these changes
Looks good to me!

2022-08-10 15:07 UTC, merged